name: CI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15'
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '12'
    - name: Build release file
      run: ./build-release.sh
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/*.tar.gz
        file_glob: true
        tag: ${{ github.ref }}
        overwrite: true